# 
---
dataset_names:
  - arraymap
  - progenetix
  - tcga
  - dipg
sample_query_keys:
  cgroup_m:
    HELP: 'multiple "OR"; partial clinical group name matches, e.g. "colo"'
  dx_m:
    HELP: 'multiple "OR"; partial text matches queried over the diagnosis text'
  geo_m:
    HELP: 'location search'
  seer_m:
    HELP: 'multiple "OR"; partial SEER group name matches'
  text_m:
    HELP: 'multiple "OR"; partial text matches queried over various attributes'
  uid_m:
    HELP: 'multiple "OR"; start-anchored UID matches'
  cellline_m:
    HELP: 'multiple "OR"; start-anchored CELLLINEID matches'
  cellosaurus_m:
    HELP: 'multiple "OR"; start-anchored CELLOSAURUSID matches'
  icdm_m:
    HELP: 'multiple "OR"; start-anchored ICD-O 3 matches, e.g. "817"'
  icdt_m:
    HELP: 'multiple "OR"; start-anchored ICD locus code matches, e.g. "50" for breast'
  ncit_m:
    HELP: 'multiple "OR"; start-anchored NCIt code matches, e.g. "C27911" for "Chronic Lymphocytic Leukemia/Small Lymphocytic Lymphoma"'
  pmid_m:
    HELP: 'multiple "OR"; start-anchored PMID matches'
  ser_m:
    HELP: 'multiple "OR"; start-anchored series ID matches, e.g. "GSE325"'
  tags_m:
    HELP: 'multiple "OR"'
  platform_m:
    HELP: 'multiple "OR"; start-anchored array platform ID matches, e.g. "GPL60"'
  locus_m :
    HELP: 'multiple "OR"; genomic locus (+/- CNA type) to be matched; e.g. "2:15998134-16004579:1" for samples with a MYCN gain/amplification'
biosubset_types:
  NCIT:
    prefix: NCIT
    regex: '/^(?:NCIT(?:[\:\-])?)?([cC]\d+?)$/'
    label: 'NCIt Neoplasm Core'
  icdom:
    prefix: icdom
    regex: '/^(?:icdom(?:[\:\-])?\d{4}(?:\/)?\d$/'
    label: 'International Classification of Diseases in Oncology (ICD-O 3) Morphology'
  icdot:
    prefix: icdot
    regex: '/^(?:icdot(?:[\:\-])?[cC]\d{1,2}((?:\.)?\d\d?)?$/'
    label: 'International Classification of Diseases in Oncology (ICD-O 3) Topography'
  biosamples.biocharacteristics.type.id:
    regex:  '/^\w+(?:[\:\-][\w\.]+?/)?$/'
    label: "Biocharacteristics"